### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by mwakiogeofrey**
basic html css project

### CODE REVIEW

**Review by jerryowusu — CHANGES_REQUESTED** [review]
Hi @mwakiogeofrey 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are some few issues you need to fix in order to move to the next level :sunglasses:

almost there


## Highlights
Followed Github flow :heavy_check_mark: 
Gitignore working. :heavy_check_mark: 

## Required Changes ♻️

- [x] Kindly ensure that linters are set up and working properly, this will help you to maintain standard best practice whiles achieving a professional project set up
- [x] Your branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). and not just `feature branch`. This will help others to know what the branch is about just by looking at the branch name.
- [ ] Though the content of the style.css is not important in this project, it should not be empty. 
Please ensure that the .css file includes one class with styles for your header (make it in your favorite color).

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @mwakiogeofrey , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights

📌 Descriptive pull request✅
📌 Great working on the set up the project ✅
📌 Good commit messages ✅

## Required Changes ♻️
_Check the comments under the review._

- [x] As requested by the previous reviewer, you should ensure that linters are set up and working properly, this will help you to maintain standard best practices whiles achieving a professional project setup. Please kindly set up linters by following this [guide](https://github.com/microverseinc/linters-config/tree/master/html-css).

- [x] As requested by the previous reviewer, you should ensure that your CSS file includes one class that styles the heading "Hello Microverse" (make it in your favorite color).

## Optional suggestions

- [ ] From the project requirement you should add a descriptive readme.md file to your project. But you have no `readme.md` in this branch. Please kindly add the project readme.md file. You can follow microverse readme [template](https://github.com/microverseinc/readme-template) to add the rest of the sections to your project readme.md file. :pray:

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @mwakiogeofrey, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* Followed Github flow :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] As suggested by the previous reviewer, I kindly suggest that you add linters to your project. In the root project, you need to have a folder named .github. Inside this one, you need another folder named workflows. And inside the workflows folder, you need a file named linters.yml. Inside this file, you need to have the linters. The linters needed for this project can be found [here](https://github.com/microverseinc/linters-config/tree/master/html-css);
>Here is a video demo I created demostrating  the above:
>
https://user-images.githubusercontent.com/52934128/164221056-46f41b39-cb1e-4fd9-a7f9-dd47bf835439.mp4
>- [ ] Kindly ensure your linter results pass * AKA: Linter should report NO errors.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- [ ] I suggest you kindly add a [README](https://github.com/microverseinc/readme-template) file to your repo, using the Microverse [template](https://github.com/microverseinc/readme-template) as this will give users detailed information about your project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Yerimah — COMMENTED** [review]
# Status: Changes Required 🔴 

Hi @mwakiogeofrey, 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4d634a5755566852566e493378656f516f6d2f67697068792e676966

## Highlights
- GitHub flow ✅ 

 ## Required Changes ♻️

- [ ] As suggested by the previous reviewer, I kindly suggest that you also set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) to improve readability and maintainability of your code. make sure that any files that are not relevant are ignored by git. The linters needed for this project can be found [here](https://github.com/microverseinc/linters-config/tree/master/html-css);
- [ ] As suggested by the previous reviewer, To make your repository look professional, make sure to add a descriptive README.md file to your repository because a README file explains what your project is about and how we can install or use it. You can use the Microverse [README template](https://github.com/microverseinc/readme-template/blob/master/README.md) to create yours.
- [ ] As requested by the previous reviewer, you should ensure that your CSS file includes one class that styles the heading "Hello Microverse" (make it in your favorite color).
- [ ] You must make sure to continue using this branch until it is approved. You are not allowed to merge until approval is given from a code reviewer after you have met the project requirements.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
